### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by andreasbenzing** [koproductions-code/ha-groheblue#5]
I get the following error when trying to dispense water:

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:526
First occurred: 10:51:48 PM (1 occurrences)
Last logged: 10:51:48 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/groheblue/__init__.py", line 91, in handle_tap_water
    target = call.data.get("device_id")[0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by koproductions-code** [comment]
First: Does your device even show up in the integration? 

The first thing that came to my mind is that it seems like there is no target device given as a parameter. Did you select the Grohe Blue device in the targets section in the UI? Also maybe try setting up the integration again, there could have failed something on setup. 

If there's still an issue, can you tell me what your input was for running the action (target, type, amount) and where you called it from to help me reproduce the issue?
